name: 'Firmware Compile Action'
description: 'Unzip libraries and compile firmware'
inputs:
  enable-warnings-report:
    description: 'Enable warnings report'
    default: 'false'
  enable-deltas-report:
    description: 'Enable deltas report'
    default: 'false'
  sketches-report-path:
    description: 'Sketches report path'
    default: 'sketches-reports'
runs:
  using: 'composite'
  steps:
    - name: Unzip libraries
      shell: bash
      run: |
        unzip -q ${{ github.workspace }}/libs/Adafruit-GFX-Library-1.11.10.zip -d ${{ github.workspace }}/libs/
    - name: Compile firmware
      uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          - ${{ github.workspace }}/src/firmware
        fqbn: esp32:esp32:esp32
        platforms: |
          - name: esp32:esp32
            source-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.14/package_esp32_index.json
            version: 2.0.14
        libraries: |
          - source-path: ${{ github.workspace }}/libs/Adafruit-GFX-Library-1.11.10
          - source-url: https://github.com/MatheusAlvesA/ArduinoAsync.git
            version: latest
          - name: Adafruit SSD1306
            version: 2.5.11
          - name: Adafruit SH110X
            version: 2.1.10
          - name: ArduinoJson
            version: 7.1.0
          - name: ArduinoWebsockets
            version: 0.5.3
          - source-url: https://github.com/mathieucarbou/ESPAsyncWebServer.git
            version: 3.1.5
          - source-url: https://github.com/mathieucarbou/AsyncTCP.git
            version: 3.2.4
          - name: BH1750_WE
            version: 1.1.10
          - source-url: https://github.com/fabianoriccardi/melody-player.git
            version: 2.4.0
          - name: NTPTime
            version: 1.2.1
          - name: FastLED
            version: 3.7.0
          - name: WiFiManager
            version: 2.0.17
          - name: arduino-sht
            version: 1.2.5
          - name: forcedBMX280
            version: 1.1.2
          - name: home-assistant-integration
            version: 2.1.0
        enable-warnings-report: ${{ inputs.enable-warnings-report }}
        enable-deltas-report: ${{ inputs.enable-deltas-report }}
        sketches-report-path: ${{ inputs.sketches-report-path }}
        cli-compile-flags: |
          - --export-binaries
          - --warnings=default
