name: 'Firmware Compile Action'
description: 'Unzip libraries and compile firmware'
inputs:
  project-folder:
    description: 'Project folder'
    default: 'firmware'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio-${{ hashFiles('${{ inputs.project-folder }}/platformio.ini') }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install PlatformIO Core
      shell: bash
      run: pip install --upgrade platformio
    - name: Build ${{ inputs.project-folder }}
      shell: bash
      run: pio run -d ${{ inputs.project-folder }} -v
