name: 'Upload Flasher to Github Pages'
description: 'Upload Flasher to Github Pages'
inputs:
  binary_path:
    description: 'Path to the binaries folder'
    default: ''
  beta_binary_path:
    description: 'Path to the beta binaries folder'
    default: ''
  lite_binary_path:
    description: 'Path to the lite binaries folder'
    default: ''
  version:
    description: 'Version of the binary'
    default: ''
  beta_build:
    description: 'Beta build number'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Copy bin to flasher
      if: ${{ inputs.binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.binary_path }}/firmware.bin ${{ github.workspace }}/flasher/bins/jaam.fw.bin
        cp -f ${{ inputs.binary_path }}/bootloader.bin ${{ github.workspace }}/flasher/bins/jaam.bootloader.bin
        cp -f ${{ inputs.binary_path }}/partitions.bin ${{ github.workspace }}/flasher/bins/jaam.partitions.bin
    - name: Change version in flasher
      if: ${{ inputs.binary_path != '' }}
      shell: bash
      run: |
        sed -i 's/>Встановити JAAM [0-9.]*</>Встановити JAAM ${{ inputs.version }}</' ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}",/' ${{ github.workspace }}/flasher/manifest.json
    - name: Copy beta bin to flasher
      if: ${{ inputs.beta_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.beta_binary_path }}/firmware.bin ${{ github.workspace }}/flasher/bins/jaam.fw.beta.bin
        cp -f ${{ inputs.beta_binary_path }}/bootloader.bin ${{ github.workspace }}/flasher/bins/jaam.bootloader.beta.bin
        cp -f ${{ inputs.beta_binary_path }}/partitions.bin ${{ github.workspace }}/flasher/bins/jaam.partitions.beta.bin
    - name: Change beta version in flasher
      if: ${{ inputs.beta_binary_path != '' }}
      shell: bash
      run: |
        sed -i 's/>Встановити JAAM [0-9.]* Beta [0-9]*</>Встановити JAAM ${{ inputs.version }} Beta ${{ inputs.beta_build }}</' ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}-b${{ inputs.beta_build }}",/' ${{ github.workspace }}/flasher/manifest-beta.json
    - name: Copy lite bin to flasher
      if: ${{ inputs.lite_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.lite_binary_path }}/firmware.bin ${{ github.workspace }}/flasher/bins/jaam.fw.lite.bin
        cp -f ${{ inputs.lite_binary_path }}/bootloader.bin ${{ github.workspace }}/flasher/bins/jaam.bootloader.lite.bin
        cp -f ${{ inputs.lite_binary_path }}/partitions.bin ${{ github.workspace }}/flasher/bins/jaam.partitions.lite.bin
    - name: Change lite version in flasher
      if: ${{ inputs.lite_binary_path != '' }}
      shell: bash
      run: |
        sed -i 's/>Встановити JAAM [0-9.]* Lite</>Встановити JAAM ${{ inputs.version }} Lite</' ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}",/' ${{ github.workspace }}/flasher/manifest-lite.json
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '${{ github.workspace }}/flasher'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
