name: 🅱️ Release BETA Firmware
on:
  workflow_dispatch:
    inputs:
        release-version:
          description: 'Beta version, ex. 3.6 or 3.6.1'
          required: true
          type: string
run-name: Release BETA ${{ inputs.release-version }}-b${{ github.run_number }}
env:
  BETA_VERSION: ${{ inputs.release-version }}-b${{ github.run_number }}
  RELEASE_TITLE: Beta ${{ inputs.release-version }}-b${{ github.run_number }}
jobs:
  release_beta_firmware:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
    #   contents: write
    #   pages: write
    #   id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Replace version in firmware source
        run: |
          sed -i 's/VERSION = ".*";/VERSION = "${{ env.BETA_VERSION }}";/' ${{ github.workspace }}/src/firmware/firmware.ino
      - name: Compile firmware
        uses: ./.github/workflows/firmware-compile
      - name: Copy release files to bin folder
        run: |
          mkdir -p ${{ github.workspace }}/bin_beta/
          cp -f ${{ github.workspace }}/src/firmware/build/esp32.esp32.esp32/firmware.ino.bin ${{ github.workspace }}/bin_beta/${{ env.BETA_VERSION }}.bin
          cp -f ${{ github.workspace }}/src/firmware/build/esp32.esp32.esp32/firmware.ino.bin ${{ github.workspace }}/bin_beta/latest_beta.bin
          cp -f ${{ github.workspace }}/src/firmware/build/esp32.esp32.esp32/firmware.ino.bin ${{ github.workspace }}/JAAM_${{ env.BETA_VERSION }}.bin
      - name: Leave only 3 recent BETA builds
        run: |
          cd ${{ github.workspace }}/bin_beta/
          ls -tp | grep -v '/$' | tail -n +5 | xargs -I {} rm -- {}
          cd ${{ github.workspace }}
      - name: Commit changes
        id: commit_changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Beta ${{ env.BETA_VERSION }}"
          file_pattern: ${{ github.workspace }}/bin_beta/
      - name: Create Beta Pre Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/JAAM_${{ env.BETA_VERSION }}.bin
          name: ${{ env.RELEASE_TITLE }}
          commit: ${{ steps.commit_changes.outputs.commit_hash }}
          tag: ${{ env.BETA_VERSION }}
          generateReleaseNotes: true
          allowUpdates: true
          prerelease: true
          makeLatest: false
      - name: Copy bin to flasher
        run: |
          cp -f ${{ github.workspace }}/JAAM_${{ env.BETA_VERSION }}.bin ${{ github.workspace }}/pages/bins/jaam_beta.bin
      - name: Change version in flasher
        run: |
          sed -i 's/>Встановити JAAM [1-9]\d*(\.[1-9]\d*)* Beta</>Встановити JAAM ${{ inputs.release-version }} Beta</' ${{ github.workspace }}/pages/index.html
          sed -i 's/"version": ".*",/"version": "${{ env.BETA_VERSION }}",/' ${{ github.workspace }}/pages/manifest-beta.json
      - name: Upload flasher to Github Pages
        uses: ./.github/workflows/.github/workflows/upload-pages
      # - name: Setup Pages
      #   uses: actions/configure-pages@v4
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: '${{ github.workspace }}/pages'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
      - name: Update server test bin list
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            cd /root/ukraine_alarm_map/deploy/
            git fetch --all
            git checkout ${{ github.ref_name }}
            git pull
            bash redeploy_update_server.sh -s '/root/ukraine_alarm_map/bin' -sb '/root/ukraine_alarm_map/bin_beta' -m ${{ secrets.MEMCACHED_HOST }}

