name: 🧪 Deploy Dev Websockets
on: workflow_dispatch

run-name: Deploy Dev Websockets from '${{ github.ref_name }}' branch
jobs:
    deploy_websocket_dev:
        runs-on: ubuntu-latest
        steps:
          - name: Redeploy Dev WebSockets
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.SERVER_IP }}
              username: ${{ secrets.SERVER_SSH_USER }}
              password: ${{ secrets.SERVER_SSH_PASSWORD }}
              script: |
                cd /root/ukraine_alarm_map/deploy/
                git fetch --all
                git checkout ${{ github.ref_name }}
                git pull
                bash redeploy_websocket_server_dev.sh -m ${{ secrets.MEMCACHED_HOST }} -s ${{ secrets.API_SECRET }} -i ${{ secrets.MEASUREMENT_ID }}
