name: ⚡ Deploy Flasher
on: workflow_dispatch
jobs:
  deploy_flasher:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload flasher to Github Pages
      uses: ./.github/workflows/upload-pages
    